[package]
name = "cliconf"
version = "0.1.3"
edition = "2021"
description = "Dead-simple configuration for Rust CLI tools."
repository = "https://github.com/computerdane/cliconf"
license = "MIT"
exclude = [".envrc", "flake*"]

[dependencies]
dirs = "6.0.0"
regex = "1.11.1"
serde_json = "1.0.140"
